In [2]:
import numpy as np

In [9]:
#Transpose matrix

a=np.array([[1,2,3],
            [4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [10]:
print(np.transpose(a))

[[1 4]
 [2 5]
 [3 6]]


In [11]:
#addition of two 1D matrix

x=np.array([1,2,3])
y=np.array([4,5,6])
print(np.add(x,y))

[5 7 9]
