In [1]:
import numpy as np

In [3]:
#task 

p=np.arange(0,18)
q=np.arange(20,38)
print('p= ',p)
print('q= ',q)
sum=p+q
print('sum= ',sum)
sum=sum.reshape(6,3)
print(sum)

p=  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]
q=  [20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]
sum=  [20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54]
[[20 22 24]
 [26 28 30]
 [32 34 36]
 [38 40 42]
 [44 46 48]
 [50 52 54]]
